src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Asserts;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 * @ORM\Table(name="products")
 */
class Product
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Asserts\NotBlank(message="Este valor não deve ficar em branco.")
     * @Groups({"productList"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Asserts\NotBlank(message="Este valor não deve ficar em branco.")
     * @Asserts\Length(min=30, minMessage="Descrição deve ter pelos menos 30 caracteres!")
     * @Groups({"productList"})
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     * @Asserts\NotBlank(message="Este valor não deve ficar em branco.")
     */
    private $body;

    /**
     * @ORM\Column(type="integer")
     * @Asserts\NotBlank(message="Este valor não deve ficar em branco.")
     * @Groups({"productList"})
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"name"})
     * @Groups({"productList"})
     */
    private $slug;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="product")
     * @Asserts\NotBlank()
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=ProductPhoto::class, mappedBy="product", orphanRemoval=true, cascade={"persist"})
     */
    private $productPhotos;

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->productPhotos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * @Groups({"productList"})
     */
    public function getFloatPrice(): ?float
    {
        $price= $this->getPrice();
        return $price / 100;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @Groups({"productList"})
     */
    public function getThumb()
    {
        if(!$this->productPhotos->count())
            return null;

        return $this->productPhotos->first()->getPhoto();
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection|ProductPhoto[]
     */
    public function getProductPhotos(): Collection
    {
        return $this->productPhotos;
    }

    public function addManyProductPhoto(array $productPhotoEntities)
    {
        foreach ($productPhotoEntities as $entity) {
            $this->addProductPhoto($entity);
        }
        return $this;
    }

    public function addProductPhoto(ProductPhoto $productPhoto): self
    {
        if (!$this->productPhotos->contains($productPhoto)) {
            $this->productPhotos[] = $productPhoto;
            $productPhoto->setProduct($this);
        }

        return $this;
    }

    public function removeProductPhoto(ProductPhoto $productPhoto): self
    {
        if ($this->productPhotos->removeElement($productPhoto)) {
            // set the owning side to null (unless already changed)
            if ($productPhoto->getProduct() === $this) {
                $productPhoto->setProduct(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <title>{% block title %}{% endblock %} Gerenciador Loja</title>

    {{ encore_entry_link_tags('app') }}

    {% block stylesheets %}{% endblock %}

    <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">
</head>
<body>
<nav class="navbar navbar-dark navbar-expand-lg sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Gerenciador Loja</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
   <div class="collapse navbar-collapse justify-content-end">
       <ul class="navbar-nav px-3">
           {% if is_granted('IS_AUTHENTICATED_FULLY') %}

               <li class="nav-item text-nowrap">
                   <a class="nav-link" href="#">{{ app.user.firstName }}</a>
               </li>

               <li class="nav-item text-nowrap">
                   <a class="nav-link" href="{{ path('app_logout') }}">Logout</a>
               </li>

           {% endif %}
       </ul>
   </div>
</nav>

<div class="container-fluid">
    <div class="row">

        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="sidebar-sticky pt-3">
                <ul class="nav flex-column">

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Administrativo</span>
                    </h6>
                    {% if is_granted('ROLE_ADMIN') %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('admin_users_index') }}">
                                <span data-feather="file"></span>
                                Usuários
                            </a>
                        </li>
                    {% endif %}

                    {% if  is_granted('ROLE_MANAGER') %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('admin_products_index') }}">
                                <span data-feather="file"></span>
                                Produtos
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ path('admin_categories_index') }}">
                                <span data-feather="file"></span>
                                Categorias
                            </a>
                        </li>

                    {% endif %}
                </ul>
            </div>
        </nav>


        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4 mt-5">

            <div class="col-12">
                {% include 'admin/includes/messages.html.twig' %}
            </div>

            {% block body %}{% endblock %}
        </main>
    </div>
</div>
{{ encore_entry_script_tags('app') }}

{% block javascripts %}{% endblock %}
</body>
</html>

templates/cart.html.twig
{% extends 'front.html.twig' %}

{% block body %}
    <div class="row mb-3">
        <div class="col-12">
            <h2>Carrinho de Compras</h2>
            <hr>
        </div>
        <div class="col-12">
            {% if cart|length >= 1 %}
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Item</th>
                        <th>Preço</th>
                        <th>Quantidade</th>
                        <th>Subtotal</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% set total = 0 %}
                    {% for c in cart %}
                        <tr>
                            <td>{{ c['name'] }}</td>
                            <td>{{ 'R$ ' ~ c['price']|number_format(2, ',','.') }}</td>
                            <td>{{ c['amount'] }}</td>
                            <td>
                                {% set subtotal =c['price'] * c['amount'] %}
                                {{ 'R$ ' ~ subtotal|number_format(2, ',','.') }}

                                {% set total = total + subtotal %}
                            </td>
                            <td><a href="{{ path('home_cart_remove', {item: c['slug']}) }}" class="btn btn-sm btn-danger">Remover</a></td>
                        </tr>
                    {% endfor %}
                        <tr>
                            <td colspan="3" class="text-right">Total: </td>
                            <td colspan="2">{{ 'R$ ' ~ total|number_format(2, ',','.') }}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="col-12 d-flex justify-content-between align-items-center">
                    <a href="{{ path('home_cart_destroy') }}" class="btn btn-lg btn-danger">Cancelar Compra</a>
                    <a href="{{ path('home_checkout') }}" class="btn btn-lg btn-success">Finalizar Pagamento</a>
                </div>
            {% else %}
                <div class="alert alert-warning">Sem produtos no carrinho...</div>
            {% endif %}
        </div>

    </div>
{% endblock %}

templates/category.html.twig
{% extends 'front.html.twig' %}

{% block body %}
    <div class="row mb-3">
        <div class="col-12">
            <h2>Categoria: {{ category }}</h2>
            <hr>
        </div>
        {% if productsPaginated|length %}
            {% for key, product in productsPaginated %}
                <div class="col-3">
                    <div class="card">
                        {% if product.getProductPhotos.count() %}
                            <img src="{{ asset('/uploads/products/' ~ product.getProductPhotos.first().photo) }}" class="card-img-top" alt="...">
                        {% else %}
                            <img src="{{ asset('images/no-photo.jpg') }}" alt="" class="img-fluid">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <a href="{{ path('product_single', {'slug': product.slug}) }}">Ver Produto</a>
                        </div>
                    </div>
                </div>
                {% if(key + 1) % 4 == 0 %} <div class="row mb-3"></div> {% endif %}
            {% endfor %}
            <hr>
            <div class="col-12">
                <div class="pagination">
                    {{ knp_pagination_render(productsPaginated) }}
                </div>
            </div>
        {% else %}
            <div class="col-12">
                <strong>Categoria não possui produtos cadastrados...</strong>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/checkout.html.twig
{% extends 'front.html.twig' %}

{% block title %}Realizar Pagamento{% endblock %}

{% block body %}
    <div class="row mt-5">
        <div class="col-6">
            <div class="row">
                <div class="col-12">
                    <h4>Dados Pagamento</h4>
                    <hr>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-12">
                    <label>Número Cartão</label>
                    <input type="text" class="form-control" name="card_number">
                </div>

                <div class="form-group col-12">
                    <label>Nome Cartão</label>
                    <input type="text" class="form-control" name="card_name">
                </div>

            </div>

            <div class="row">

                <div class="form-group col-4">
                    <label>Mês Cartão</label>
                    <input type="text" class="form-control" name="card_month">
                </div>

                <div class="form-group col-4">
                    <label>Ano Cartão</label>
                    <input type="text" class="form-control" name="card_year">
                </div>

            </div>

            <div class="row">

                <div class="form-group col-4">
                    <label>Código de Segurança</label>
                    <input type="text" class="form-control" name="card_cvv">
                </div>

            </div>

            <div class="row">

                <div class="col-12">
                    <button type="submit" class="btn btn-success btn-lg proccessPayment">Realizar Pagamento</button>
                </div>

            </div>
        </div>
        <div class="col-6 border-left pl-5">
            <div class="row">
                <div class="col-12">
                    <h4>Pedido</h4>
                    <hr>
                </div>
                {% set total = 0 %}

                {% for item in cart %}
                    <div class="col-12">
                        <p>
                            {% set subtotal = item.amount*item.price %}
                            {% set total = total + subtotal %}

                            {{ item.amount }}x {{ item.name }} (R$ {{ item.price|number_format(2, ',', '.') }}) - Subtotal: R$ {{ subtotal|number_format('2', ',', '.') }}
                        </p>
                    </div>
                {% endfor %}

                <div class="col-12">
                    <hr>
                    <h5>Total: R$ {{ total|number_format(2, ',', '.') }}</h5>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        let processPaymentButton = document.querySelector('button.proccessPayment');

        processPaymentButton.addEventListener('click', function (e){
            e.preventDefault();

            alert('Pagamento Relizado...');

            location.href = "{{ path('home_checkout_finished') }}";
        })
    </script>
{% endblock %}

templates/front.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">

    <title>{% block title %}{% endblock %}</title>

    {{ encore_entry_link_tags('app') }}

    {% block stylesheets %}{% endblock %}

</head>
<body>
    <!-- NavBar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if app.request.attributes.get('_route') == 'home' %} active {% endif %}" aria-current="page" href="{{ path('home') }}">Home</a>
                    </li>
                    {%  for category in categories.findAll() %}

                        {% set pathCategory = path('home_category',{'slug': category.slug}) %}

                        <li class="nav-item">

                            <a class="nav-link {% if pathCategory == app.request.pathInfo %} active {% endif %}" aria-current="page" href="{{ pathCategory }}">{{ category.name }}</a>

                        </li>

                    {% endfor %}
                    <li class="nav-item">
                        <a class="nav-link {% if app.request.attributes.get('_route') == 'home_cart' %} active {% endif %}" aria-current="page" href="{{ path('home_cart') }}">Carrinho</a>
                    </li>

                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{{ path('home_cart') }}" class="nav-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </svg>
                            {% if app.request.session.has('cart') %}
                                <span class="badge badge-danger">
                                    {{ app.request.session.get('cart')|length }}
                                </span>
                            {% endif %}
                        </a>
                    </li>
                </ul>
                <form class="d-flex form-inline" action="{{ path('home_search') }}">
                    <input class="form-control me-2" type="search"  name="s" placeholder="Encontre o seu produto" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="message">
            {% include 'admin/includes/messages.html.twig'%}

        </div>
        {% block body %}{% endblock %}
    </div>
    {{ encore_entry_script_tags('app') }}

    {% block javascripts %}{% endblock %}
</body>
</html>

templates/index.html.twig
{% extends 'front.html.twig' %}

{% block body %}
    <div id="app">Carregando...</div>
{% endblock %}

templates/register.html.twig
{% extends 'front.html.twig' %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-success btn-lg">Criar Conta</button>
    {{ form_end(form) }}
{% endblock %}

templates/search.html.twig
{% extends 'front.html.twig' %}

{% block body %}
    <div class="row mb-3">
        <div class="col-12">
            <h2>Resultado busca: {{ search }}</h2>
            <hr>
        </div>
        {% if products|length %}
            {% for key, product in products %}
                <div class="col-3">
                    <div class="card">
                        {% if product.getProductPhotos.count() %}
                            <img src="{{ asset('/uploads/products/' ~ product.getProductPhotos.first().photo) }}" class="card-img-top" alt="...">
                        {% else %}
                            <img src="{{ asset('images/no-photo.jpg') }}" alt="" class="img-fluid">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.description }}</p>
                            <a href="{{ path('product_single', {'slug': product.slug}) }}">Ver Produto</a>
                        </div>
                    </div>
                </div>
                {% if(key + 1) % 4 == 0 %} <div class="row mb-3"></div> {% endif %}
            {% endfor %}
            <hr>
            <div class="col-12">
                <div class="pagination">
                    {{ knp_pagination_render(products) }}
                </div>
            </div>
        {% else %}
            <div class="col-12">
                <strong>Categoria não possui produtos cadastrados...</strong>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/single.html.twig
{% extends 'front.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-6">
            {% if product.getProductPhotos.count() %}
                <div class="row">
                    <div class="col-3 pr-2">
                        {% for photo in product.productPhotos %}
                        <img src="{{ asset('/uploads/products/' ~ photo.photo) }}" class="card-img-top" alt="..." class="img-fluid mb-2">
                        {% endfor %}
                    </div>
                    <div class="col-9 pl-0">
                        <img src="{{ asset('/uploads/products/' ~ product.getProductPhotos.first().photo) }}" class="card-img-top" alt="...">
                    </div>
                </div>

            {% else %}
                <img src="{{ asset('images/no-photo.jpg') }}" alt="" class="img-fluid">
            {% endif %}
        </div>
        <div class="col-6">
            <h5>{{ product.name }}</h5>
            <p>{{ product.description }}</p>
            <h3>R$ {{ product.floatPrice|number_format(2, ',', '.') }}</h3>
            <form action="{{ path('home_cart_add', {item: product.slug}) }}" class="mt-3" method="post">
                <div class="form-group">
                    <label for="">Quantidade</label>
                    <input type="number" name="amount" id="" value="1" class="form-control col-2">
                </div>
                <button type="submit" class="btn btn-danger btn-lg">Comprar</button>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <hr>
            {{ product.body }}
        </div>
    </div>
{% endblock %}

templates/thanks.html.twig
{% extends 'front.html.twig' %}

{% block title %}Obrigado por sua compra!{% endblock %}

{% block body %}
    <div class="row mt-5">
        <div class="col-12">
            <div class="row">

                <div class="col-12">
                    <h4>Obrigado por sua compra!</h4>
                    <hr>
                </div>

            </div>

        </div>
        <div class="col-12 pt-5">
            <div class="row d-flex justify-content-between align-items-center">
                <div class="col-6"><h5>Pedido</h5></div>
                <div class="col-6 text-right"><h5>N˚ #122233</h5></div>
            </div>

            <div class="row">
                <div class="col-12">
                    <hr>
                </div>
                {% set total = 0 %}

                {% for item in cart %}
                    <div class="col-12">
                        <p>
                            {% set subtotal = item.amount*item.price %}
                            {% set total = total + subtotal %}

                            {{ item.amount }}x {{ item.name }} (R$ {{ item.price|number_format(2, ',', '.') }}) - Subtotal: R$ {{ subtotal|number_format('2', ',', '.') }}
                        </p>
                    </div>
                {% endfor %}

                <div class="col-12">
                    <hr>
                    <strong>Total: R$ {{ total|number_format(2, ',', '.') }}</strong>
                </div>
            </div>
        </div>
    </div>
{% endblock %}